### PR TITLE
Lighting a fire with some really old, flammable Ruby.

### PR DESCRIPTION
**Pull request by reidblomquist**
Opening for review - updated w/ work on your master - conversation starter to see where we can take this \o/

### CODE REVIEW

**Comment by onewheelskyward** [comment]
Whee!

**Comment by reidblomquist** [comment]
@onewheelskyward we had talked about maybe making this a separate plugin/gem - what are your thoughts now on making this a lita-ows-forecast-io addon or something?

**Comment by onewheelskyward** [comment]
welp

**Comment by onewheelskyward** [comment]
@reidblomquist Lemme look at it.  I've been seriously considering rewriting this whole thing in node and making it serverless.

**Pull request closed without merging**
